#!/usr/bin/env bash


# ╔═══════════════════╗
# ║  TEXT FORMATTING  ║
# ╚═══════════════════╝

BOLD=$(tput bold)           # bold
UNDERLINE=$(tput smul)      # underline

BG_BLACK=$(tput setab 0)    # black
BG_BLUE=$(tput setab 4)     # blue
BG_CYAN=$(tput setab 6)     # cyan
BG_GREEN=$(tput setab 2)    # green
BG_MAGENTA=$(tput setab 5)  # magenta
BG_RED=$(tput setab 1)      # red
BG_WHITE=$(tput setab 7)    # white
BG_YELLOW=$(tput setab 3)   # yellow

FG_BLACK=$(tput setaf 0)    # black
FG_BLUE=$(tput setaf 4)     # blue
FG_CYAN=$(tput setaf 6)     # cyan
FG_GREEN=$(tput setaf 2)    # green
FG_MAGENTA=$(tput setaf 5)  # magenta
FG_RED=$(tput setaf 1)      # red
FG_WHITE=$(tput setaf 7)    # white
#FG_WHITE=$(tput setaf 15)   # white
FG_YELLOW=$(tput setaf 3)   # yellow
#FG_YELLOW=$(tput setaf 11)  # yellow

CLEAR=$(tput sgr0)          # clear

export BOLD
export UNDERLINE

export BG_BLACK
export BG_BLUE
export BG_CYAN
export BG_GREEN
export BG_MAGENTA
export BG_RED
export BG_WHITE
export BG_YELLOW

export FG_BLACK
export FG_BLUE
export FG_CYAN
export FG_GREEN
export FG_MAGENTA
export FG_RED
export FG_WHITE
export FG_YELLOW

export CLEAR


# ╔═════════╗
# ║  ICONS  ║
# ╚═════════╝

STAR_F='\u2605'             # STAR FULL
TRIANGLE_F_D='\u25bc'       # TRIANGLE FULL DOWN

export STAR_F
export TRIANGLE_F_D
