#!/usr/bin/env bash

# PUBLIC API
function join {
    local IFS="$1"
    shift
    echo "$*"
}

### USAGE ###
# NAME=eolo
# NANI=(brontolo cucciolo dotto eolo gongolo mammolo pisolo)
# if in_array "$NAME" "${NANI[@]}"; then echo "c'è"; else echo "non c'è"; fi
function in_array() {
    for i in "${@:2}"; do
        if [ "$i" == "$1" ]; then
            return 0
        fi
    done
    return 1
}
